# Generated by Django 5.1.2 on 2024-10-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harshini', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
